services:
  authentik:
    container_name: Authentik
    image: ghcr.io/goauthentik/server:${AUTHENTIK_VERSION:-2026.5}
    command: server
    ports:
      - 6000:9000
      - 6001:9443
    user: ${PUID:-0}:${PGID:-0}
    shm_size: 512mb
    environment:
      - PUID=${PUID:-0}
      - PGID=${PGID:-0}
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_POSTGRESQL__HOST=authentik-database
      - AUTHENTIK_POSTGRESQL__NAME=${AUTHENTIK_DATABASE_SCHEMA:-authentik}
      - AUTHENTIK_POSTGRESQL__USER=${AUTHENTIK_DATABASE_USERNAME:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_DATABASE_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${PATH_APPDATA}/authentik/data:/data
    networks:
      - app-authentik
    restart: unless-stopped
    depends_on:
      authentik-database:
        condition: service_healthy

  authentik-worker:
    container_name: Authentik-Worker
    image: ghcr.io/goauthentik/server:${AUTHENTIK_VERSION:-2026.5}
    command: worker
    shm_size: 512mb
    user: ${PUID:-0}:${PGID:-0}
    environment:
      - PUID=${PUID:-0}
      - PGID=${PGID:-0}
      - AUTHENTIK_POSTGRESQL__HOST=authentik-database
      - AUTHENTIK_POSTGRESQL__NAME=${AUTHENTIK_DATABASE_SCHEMA:-authentik}
      - AUTHENTIK_POSTGRESQL__USER=${AUTHENTIK_DATABASE_USERNAME:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_DATABASE_PASSWORD}
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PATH_APPDATA}/authentik/data:/data
      - ${PATH_APPDATA}/authentik/certs:/certs
    networks:
      - app-authentik
    restart: unless-stopped
    depends_on:
      authentik-database:
        condition: service_healthy
    
  authentik-database:
    container_name: Authentik-Database
    image: docker.io/library/postgres:latest
    user: ${PUID:-0}:${PGID:-0}
    environment:
      - PUID=${PUID:-0}
      - PGID=${PGID:-0}
      - POSTGRES_DB=${AUTHENTIK_DATABASE_SCHEMA:-authentik}
      - POSTGRES_USER=${AUTHENTIK_DATABASE_USERNAME:-authentik}
      - POSTGRES_PASSWORD=${AUTHENTIK_DATABASE_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${PATH_APPDATA}/authentik/database:/var/lib/postgresql/data
    networks:
      - app-authentik
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${AUTHENTIK_DATABASE_SCHEMA} -U $${AUTHENTIK_DATABASE_USERNAME}
      timeout: 5s
    restart: unless-stopped

networks:
  app-authentik:
    name: app-authentik
    driver: bridge
