services:
  dockhand:
    container_name: Dockhand
    image: fnsys/dockhand:${DOCKHAND_VERSION:-latest}
    ports:
      - 3000:3000
    environment:
      - DISABLE_LOCAL_LOGIN=${DOCKHAND_DISABLE_LOCAL_LOGIN:-False}
      - DISABLE_WHATS_NEW=${DOCKHAND_DISABLE_WHATS_NEW:-True}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PATH_APPDATA}/dockhand:/app/data:rw
    networks:
      - app-dockhand
    restart: always

networks:
  app-dockhand:
    name: app-dockhand
    driver: bridge
